
name: Deploy

on:
  push:
    # We only run this GitHub action upon new commits to `main`
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install
        run: pnpm install

      - name: Build vite-plugin-ssr
        run: pnpm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/client
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
